{
  "bridge": {
    
  },
  "description": "HomeBridge HTTP Status Control",
  "accessories": [],
  "platforms": [
    // This is the config for this plugin  
    {
      "platform": "DysonPlatform",
      "name": "DysonPlatform",
      "accessories": [
        {
          "ip": "192.168.1.9",
          "displayName": "Silkie",
          "serialNumber": "DYSON-YN1-US-KGA0119A",
          "password": "qaTTara$2"
        },
       ]
    }
    // End of the config
  ]
}
